# Generated by Django 6.0.6 on 2026-07-04 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BacktestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата на теста')),
                ('strategy_name', models.CharField(max_length=100, verbose_name='Стратегия')),
                ('ticker', models.CharField(max_length=20, verbose_name='Актив')),
                ('initial_capital', models.FloatField(verbose_name='Начален капитал')),
                ('final_value', models.FloatField(verbose_name='Краен капитал')),
                ('roi_percentage', models.FloatField(verbose_name='Възвръщаемост (ROI %)')),
                ('max_drawdown', models.FloatField(verbose_name='Максимален спад (%)')),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('BUY', 'Покупка'), ('SELL', 'Продажба')], max_length=4, verbose_name='Действие')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('quantity', models.IntegerField(verbose_name='Количество')),
                ('date', models.CharField(max_length=20, verbose_name='Дата')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='simulator.backtestrun')),
            ],
        ),
    ]
